/* Evidence-driven, dependency-free temporal diagrams for the development recorder. */
(() => {
  'use strict';
  const COLORS = {codex:'#73d5ff',flujo:'#f5b88f',slack:'#bea8ff',github:'#cbef86',docs:'#ed9bbb',ci:'#8de0c8',docker:'#79bfff',fly:'#bea8ff',local:'#8de0c8',modal:'#ed9bbb'};
  const INK='#0b1420',TEXT='#edf3f8',MUTED='#8296ab',MONO='"Cascadia Code",Consolas,monospace',SANS='Inter,"Segoe UI",sans-serif';
  const arr=value=>Array.isArray(value)?value:[];
  const num=value=>Number.isFinite(Number(value))?Number(value):0;
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const stamp=value=>typeof value==='number'?value:Date.parse(value)||0;
  const evidence=item=>arr(item?.eventIds).length?item.eventIds:arr(item?.evidenceEventIds).length?item.evidenceEventIds:arr(item?.evidenceIds);
  const label=value=>String(value??'').replace(/\uFFFD/g,' · ').replace(/\s+/g,' ').trim();
  const source=item=>item?.source||String(item?.id||'').split(':')[0];
  const causal=item=>!/(infer|shared|reference|editorial|declared|snapshot)/i.test(item?.basis||'') && /spawn|dispatch|steer|fork|handoff|transition|completed|parent|execute/i.test(item?.kind||'');
  const compactDate=value=>{const ms=stamp(value);return ms?new Intl.DateTimeFormat('en-US',{timeZone:'America/Bogota',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(ms):'Time not captured';};
  const normalizeRef=ref=>String(ref).replace(/https:\/\/github.com\/([^/]+\/[^/]+)\/(?:pull|issues)\/(\d+).*/i,'github:$1:$2').replace(/\/$/,'');
  const upperBound=(values,target)=>{let lo=0,hi=values.length;while(lo<hi){const mid=(lo+hi)>>>1;if(values[mid]<=target)lo=mid+1;else hi=mid;}return lo;};
  const flowStamp=flow=>stamp(flow.availableFrom||flow.timestamp||flow.updatedAt||flow.createdAt||flow.firstTimestamp);
  function rr(ctx,x,y,w,h,r=12){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.moveTo(x+r,y),ctx.arcTo(x+w,y,x+w,y+h,r),ctx.arcTo(x+w,y+h,x,y+h,r),ctx.arcTo(x,y+h,x,y,r),ctx.arcTo(x,y,x+w,y,r));ctx.closePath();}
  function curveAt(path,t){const q=1-t;return {x:q*q*q*path.x1+3*q*q*t*path.c1x+3*q*t*t*path.c2x+t*t*t*path.x2,y:q*q*q*path.y1+3*q*q*t*path.c1y+3*q*t*t*path.c2y+t*t*t*path.y2};}
  function pointDistance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}

  class HistoryGraphScene {
    constructor(canvas,options={}) {
      this.canvas=canvas;this.ctx=canvas.getContext('2d');this.options=options;this.data={};this.hits=[];this.layout=null;this.lastState={};
      this.camera={x:0,y:0,scale:1};this.viewKey='';this.hover=null;this.drag=null;this.width=0;this.height=0;this.controls=[];this.infraPages=new Map();this.followKey='';this._attach();
    }
    setData(data) {
      this.data=data||{};this.events=arr(data?.events);this.eventById=new Map(this.events.map(event=>[event.id,event]));this.sessionById=new Map(arr(data?.topology?.sessions).map(session=>[session.id,session]));
      this.eventSessions=new Map();this.edgeEvents=new Map();this.machineEvents=new Map();this.referenceSources=new Map();this.sourceTimes=new Map();this.sessionTimes=new Map();
      for(const session of this.sessionById.values())for(const id of evidence(session)){if(!this.eventSessions.has(id))this.eventSessions.set(id,[]);this.eventSessions.get(id).push(session);}
      for(const edge of arr(data?.topology?.agentEdges))for(const id of evidence(edge)){if(!this.edgeEvents.has(id))this.edgeEvents.set(id,[]);this.edgeEvents.get(id).push(edge);}
      // Repeated dispatches share one readable connection. Each event still has its own pulse.
      const groups=new Map();for(const edge of arr(data?.topology?.agentEdges)){const key=[edge.from,edge.to,edge.kind,edge.executed===false?'snapshot':'recorded'].join('|');let aggregate=groups.get(key);if(!aggregate){aggregate={...edge,eventIds:[],eventSet:new Set(),instances:0,originalEdgeIds:[]};groups.set(key,aggregate);}aggregate.instances++;aggregate.originalEdgeIds.push(edge.id);if(stamp(edge.timestamp)<stamp(aggregate.timestamp))aggregate.timestamp=edge.timestamp;for(const id of evidence(edge))aggregate.eventSet.add(id);}
      this.aggregatedEdges=[...groups.values()].map(edge=>{edge.eventIds=[...edge.eventSet];delete edge.eventSet;return edge;});
      this.agentLayouts=new Map();this.flowLayouts=new Map();this.flowById=new Map(arr(data?.topology?.flows).map(flow=>[flow.id,flow]));this.flowDefinitions=new Map();this.flowAnchor=null;
      for(const flow of this.flowById.values()){const key=flow.flowDefinitionId||flow.id;if(!this.flowDefinitions.has(key))this.flowDefinitions.set(key,[]);this.flowDefinitions.get(key).push(flow);}for(const versions of this.flowDefinitions.values())versions.sort((a,b)=>flowStamp(a)-flowStamp(b)||String(a.id).localeCompare(String(b.id)));
      for(const event of this.events){
        if(!this.sourceTimes.has(event.source))this.sourceTimes.set(event.source,[]);this.sourceTimes.get(event.source).push(stamp(event.timestamp));
        const machineId=event.metadata?.machineId;
        if(machineId){if(!this.machineEvents.has(machineId))this.machineEvents.set(machineId,[]);this.machineEvents.get(machineId).push(event);}
        for(const ref of arr(event.references)){const key=normalizeRef(ref);if(!this.referenceSources.has(key))this.referenceSources.set(key,new Map());const sources=this.referenceSources.get(key),time=stamp(event.timestamp);sources.set(event.source,Math.min(sources.get(event.source)??Infinity,time));}
      }
      for(const events of this.machineEvents.values())events.sort((a,b)=>stamp(a.timestamp)-stamp(b.timestamp));
      for(const times of this.sourceTimes.values())times.sort((a,b)=>a-b);
      for(const session of this.sessionById.values()){const s=source(session);if(!this.sessionTimes.has(s))this.sessionTimes.set(s,[]);this.sessionTimes.get(s).push(stamp(session.startedAt));}for(const times of this.sessionTimes.values())times.sort((a,b)=>a-b);
      this._version=(this._version||0)+1;this.layout=null;this.viewKey='';
    }
    resetView(){this.camera={x:0,y:0,scale:1};this.layout=null;this.render(this.lastState);}
    fitView(){const bounds=this._bounds();if(!bounds)return;const scale=clamp(Math.min((this.width-40)/bounds.w,(this.height-120)/bounds.h),.06,1);this.camera={scale,x:20-bounds.x*scale+(this.width-40-bounds.w*scale)/2,y:24-bounds.y*scale};this.render(this.lastState);}
    zoomBy(factor){this._zoom(factor,this.width/2,this.height/2);this.render(this.lastState);}
    destroy(){for(const [name,fn,options] of this.listeners||[])this.canvas.removeEventListener(name,fn,options);}
    _attach() {
      this.listeners=[];const on=(name,fn,options)=>{this.canvas.addEventListener(name,fn,options);this.listeners.push([name,fn,options]);};
      on('pointerdown',event=>{if(!this._enabled())return;const p=this._point(event);if(this._inMinimap(p)){this._jumpMinimap(p);this.drag={minimap:true,moved:true};this.render(this.lastState);}else this.drag={x:p.x,y:p.y,cameraX:this.camera.x,cameraY:this.camera.y,moved:false};this.canvas.setPointerCapture?.(event.pointerId);});
      on('pointermove',event=>{if(!this._enabled())return;const p=this._point(event);if(this.drag?.minimap){this._jumpMinimap(p);this.render(this.lastState);return;}if(this.drag){const dx=p.x-this.drag.x,dy=p.y-this.drag.y;if(Math.hypot(dx,dy)>4)this.drag.moved=true;if(this.drag.moved){this.camera.x=this.drag.cameraX+dx;this.camera.y=this.drag.cameraY+dy;this.render(this.lastState);this.canvas.style.cursor='grabbing';return;}}
        const hit=this.hitTest(p.x,p.y);this.hover=hit;this.canvas.style.cursor=hit||this._controlAt(p)||this._inMinimap(p)?'pointer':'grab';this.options.onInspect?.(hit,{x:p.x,y:p.y});this.render(this.lastState);
      });
      on('pointerup',event=>{if(!this._enabled())return;const p=this._point(event),moved=this.drag?.moved;this.drag=null;if(!moved){const control=this._controlAt(p);if(control){control.action();this.render(this.lastState);}else{const hit=this.hitTest(p.x,p.y);if(hit)this.options.onSelect?.(hit);}}this.canvas.style.cursor=this.hover?'pointer':'grab';});
      on('pointercancel',()=>{this.drag=null;});on('pointerleave',()=>{this.hover=null;this.options.onInspect?.(null);if(this._enabled())this.render(this.lastState);});
      on('wheel',event=>{if(!this._enabled()||(!event.ctrlKey&&!event.metaKey))return;event.preventDefault();const p=this._point(event);this._zoom(Math.exp(-event.deltaY*.002),p.x,p.y);this.render(this.lastState);},{passive:false});
      on('dblclick',()=>{if(this._enabled())this.resetView();});
    }
    _enabled(){return ['landscape','agents','flows','infrastructure'].includes(this.lastState.view);}
    _point(event){const rect=this.canvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};}
    _zoom(factor,x,y){const before=this.camera.scale,after=clamp(before*factor,.06,2.4),ratio=after/before;this.camera.x=x-(x-this.camera.x)*ratio;this.camera.y=y-(y-this.camera.y)*ratio;this.camera.scale=after;}
    _bounds(){const rectangles=this.hits.filter(hit=>hit.rect).map(hit=>hit.rect);if(!rectangles.length)return null;const x=Math.min(...rectangles.map(r=>r.x)),y=Math.min(...rectangles.map(r=>r.y)),right=Math.max(...rectangles.map(r=>r.x+r.w)),bottom=Math.max(...rectangles.map(r=>r.y+r.h));return{x,y,w:right-x,h:bottom-y};}
    _inMinimap(point){const m=this.minimap;return Boolean(m&&point.x>=m.x&&point.x<=m.x+m.w&&point.y>=m.y&&point.y<=m.y+m.h);}
    _jumpMinimap(point){const m=this.minimap;if(!m)return;const worldX=m.bounds.x+(point.x-m.x)/m.scale,worldY=m.bounds.y+(point.y-m.y)/m.scale;this.camera.x=this.width/2-worldX*this.camera.scale;this.camera.y=this.height/2-worldY*this.camera.scale;}
    _controlAt(point){const x=(point.x-this.camera.x)/this.camera.scale,y=(point.y-this.camera.y)/this.camera.scale;return this.controls.find(control=>x>=control.x&&x<=control.x+control.w&&y>=control.y&&y<=control.y+control.h);}
    _followFlowSelection(){const target=this.flowFollow;if(!target)return false;if(target.key===this.followKey)return false;this.followKey=target.key;const r=target.rect,c=this.camera,padding=24,bottom=this.height-88,left=r.x*c.scale+c.x,top=r.y*c.scale+c.y,right=left+r.w*c.scale,lower=top+r.h*c.scale;
      if(left>=padding&&right<=this.width-padding&&top>=padding&&lower<=bottom)return false;
      // One deterministic camera adjustment on a new recorded selection, never a frame loop.
      const oldScale=c.scale;if(r.w*c.scale>this.width-padding*2||r.h*c.scale>bottom-padding)c.scale=Math.min(c.scale,(this.width-padding*2)/r.w,(bottom-padding)/r.h);
      if(left<padding||right>this.width-padding||c.scale!==oldScale)c.x=this.width/2-(r.x+r.w/2)*c.scale;if(top<padding||lower>bottom||c.scale!==oldScale)c.y=(padding+bottom)/2-(r.y+r.h/2)*c.scale;return true;
    }
    _datedFlow(definitionId){const versions=this.flowDefinitions.get(definitionId)||[],prior=versions.filter(flow=>flowStamp(flow)<=this.now);return prior[prior.length-1]||versions[0]||null;}
    _resolveFlow(){const e=this.selection,m=e?.metadata||{},bound=this.sessionById.get(m.executingSessionId)||this.sessionById.get(m.sessionId)||(this.eventSessions.get(e?.id)||[]).find(session=>session.flowId),explicit=this.lastState.flowId;
      const hints=(explicit?[explicit]:[m.flowSnapshotId,m.flowId,bound?.flowId,m.flowDefinitionId,bound?.flowDefinitionId]).filter(Boolean);let flow=null,pinned=false;for(const hint of hints){const exact=this.flowById.get(hint);flow=exact||this._datedFlow(hint);if(flow){pinned=Boolean(exact);break;}}
      if(flow){if(!explicit)this.flowAnchor={definitionId:flow.flowDefinitionId||flow.id,snapshotId:flow.id,pinned};this.flowResolution=explicit?'Explicitly selected snapshot':'Recorded event or session attribution';return flow;}
      if(this.flowAnchor){flow=this.flowAnchor.pinned?this.flowById.get(this.flowAnchor.snapshotId):this._datedFlow(this.flowAnchor.definitionId);if(flow){this.flowResolution=this.flowAnchor.pinned?'Last attributed snapshot retained through unattributed events':'Last attributed definition; version changes follow recorded snapshot dates';return flow;}}
      const candidates=[...this.flowById.values()].sort((a,b)=>Number(/supervisor/i.test(b.label||''))-Number(/supervisor/i.test(a.label||''))||arr(b.nodes).length-arr(a.nodes).length||flowStamp(a)-flowStamp(b)||String(a.id).localeCompare(String(b.id)));
      const first=candidates[0];if(!first)return null;const definitionId=first.flowDefinitionId||first.id;this.flowAnchor={definitionId,snapshotId:first.id,pinned:false};this.flowResolution='Declared graph overview; this event has no flow attribution';return this._datedFlow(definitionId)||first;
    }
    _flowLayout(flow,cardW,cardH,margin){const definitionId=flow.flowDefinitionId||flow.id,key=[definitionId,flow.id,cardW,cardH].join('|');if(this.flowLayouts.has(key))return this.flowLayouts.get(key);
      const family=this.flowDefinitions.get(definitionId)||[flow],positioned=family.some(version=>arr(version.nodes).some(node=>Number.isFinite(Number(node.x??node.position?.x))&&Number.isFinite(Number(node.y??node.position?.y))));
      const rawFor=version=>arr(version.nodes).map((node,i)=>({...node,px:positioned?num(node.x??node.position?.x):i%3*270,py:positioned?num(node.y??node.position?.y):Math.floor(i/3)*150}));
      const union=family.flatMap(rawFor),xs=[...new Set(union.map(node=>node.px))].sort((a,b)=>a-b),ys=[...new Set(union.map(node=>node.py))].sort((a,b)=>a-b);
      // Saved coordinate order remains intact. A minimum axis separation fits the larger evidence cards.
      // The transform uses all versions of this definition, so adding/removing a node cannot jiggle existing nodes.
      const spread=(values,gap)=>{const map=new Map();let position=0;for(let i=0;i<values.length;i++){if(i)position+=Math.max(gap,(values[i]-values[i-1])*.8);map.set(values[i],position);}return map;};
      const xMap=spread(xs,cardW+32),yMap=spread(ys,cardH+26),nodes=rawFor(flow).sort((a,b)=>a.py-b.py||a.px-b.px||String(a.id).localeCompare(String(b.id))),placed=[];
      for(const node of nodes){const rect={...node,x:margin+(xMap.get(node.px)||0),y:114+(yMap.get(node.py)||0),w:cardW,h:cardH};let collision=true;while(collision){collision=false;for(const prior of placed)if(rect.x<prior.x+prior.w+16&&rect.x+rect.w+16>prior.x&&rect.y<prior.y+prior.h+18&&rect.y+rect.h+18>prior.y){rect.y=prior.y+prior.h+26;collision=true;}}placed.push(rect);}
      const result={map:new Map(placed.map(node=>[node.id,node])),positioned};this.flowLayouts.set(key,result);return result;
    }
    _agentLayout(pool,focus,cardW,cardH,margin,mobile){const key=[this._version,focus?.id||'all',pool.map(s=>s.id).sort().join(','),cardW,mobile].join('|');if(this.agentLayouts.has(key))return this.agentLayouts.get(key);
      const ordered=pool.slice().sort((a,b)=>stamp(a.startedAt)-stamp(b.startedAt)||String(a.id).localeCompare(String(b.id))),byId=new Map(ordered.map(session=>[session.id,session])),children=new Map();for(const s of ordered)if(s.parentId&&byId.has(s.parentId)){if(!children.has(s.parentId))children.set(s.parentId,[]);children.get(s.parentId).push(s);}
      const roots=ordered.filter(s=>!s.parentId||!byId.has(s.parentId)),base=[],visit=(s,depth=0)=>{if(base.length>=44||base.includes(s.id))return;base.push(s.id);for(const child of(children.get(s.id)||[]).slice(0,focus?14:2))visit(child,depth+1);};for(const root of roots)visit(root);
      const placements=[],seen=new Set();let sectionY=76,flujoStart=76;
      for(const group of ['codex','flujo']){const groupRoots=ordered.filter(s=>source(s)===group&&(!byId.has(s.parentId)||source(byId.get(s.parentId))!==group));let row=0;
        const place=(item,depth=0)=>{if(seen.has(item.id))return row;seen.add(item.id);const descendants=(children.get(item.id)||[]).filter(child=>source(child)===group);let localRow;if(mobile){localRow=row++;placements.push({item,depth,row:localRow,sectionY});for(const child of descendants)place(child,depth+1);return localRow;}if(descendants.length){const childRows=descendants.map(child=>place(child,depth+1));localRow=(childRows[0]+childRows[childRows.length-1])/2;}else localRow=row++;placements.push({item,depth,row:localRow,sectionY});return localRow;};
        for(const root of groupRoots){place(root);row+=.35;}if(group==='codex'){sectionY+=Math.max(1,row)*(cardH+30)+72;flujoStart=sectionY;}}
      const map=new Map(placements.map(p=>[p.item.id,{...p.item,x:margin+(mobile?Math.min(p.depth,3)*17:p.depth*(cardW+30)),y:p.sectionY+p.row*(cardH+30),w:cardW,h:cardH}])),result={key,map,base,byId,children,flujoStart};this.agentLayouts.set(key,result);return result;
    }
    hitTest(x,y) {
      const p={x:(x-this.camera.x)/this.camera.scale,y:(y-this.camera.y)/this.camera.scale};
      for(let i=this.hits.length-1;i>=0;i--){const hit=this.hits[i];if(hit.rect&&p.x>=hit.rect.x&&p.x<=hit.rect.x+hit.rect.w&&p.y>=hit.rect.y&&p.y<=hit.rect.y+hit.rect.h)return this._publicHit(hit);
        if(hit.path){for(let t=0;t<=1;t+=.04)if(pointDistance(curveAt(hit.path,t),p)<9/this.camera.scale)return this._publicHit(hit);}
      }return null;
    }
    _publicHit(hit){return{type:hit.type,id:hit.id,eventIds:evidence(hit.item),item:hit.item,label:hit.label||hit.item?.label||hit.item?.title||hit.id};}
    render(state={}) {
      this.lastState=state;if(!this._enabled())return;
      const rect=this.canvas.getBoundingClientRect(),width=Math.max(260,rect.width||this.canvas.clientWidth||900),height=Math.max(360,rect.height||this.canvas.clientHeight||620),dpr=Math.min(window.devicePixelRatio||1,2);
      if(this.canvas.width!==Math.round(width*dpr)||this.canvas.height!==Math.round(height*dpr)){this.canvas.width=Math.round(width*dpr);this.canvas.height=Math.round(height*dpr);}
      const changed=width!==this.width||height!==this.height;this.width=width;this.height=height;this.dpr=dpr;
      this.ctx.setTransform(dpr,0,0,dpr,0,0);this.ctx.clearRect(0,0,width,height);this.hits=[];this.controls=[];this._background();
      const selection=state.selectedEvent||((typeof state.eventCursor==='number')?this.events[state.eventCursor]:state.eventCursor)||null;this.selection=selection;this.now=stamp(state.now)||stamp(selection?.timestamp)||Date.now();
      const key=[state.view,state.sessionFilter||'',state.flowId||'',this._version,width<600?'mobile':'wide'].join('|');
      if(key!==this.viewKey||changed){this.viewKey=key;this.camera={x:0,y:0,scale:1};this.layout=null;this.hover=null;this.followKey='';}
      this.flowFollow=null;
      const ctx=this.ctx;ctx.save();ctx.translate(this.camera.x,this.camera.y);ctx.scale(this.camera.scale,this.camera.scale);
      if(state.view==='landscape')this._landscape();else if(state.view==='agents')this._agents();else if(state.view==='flows')this._flows();else this._infrastructure();ctx.restore();if(['flows','agents'].includes(state.view)&&this._followFlowSelection())return this.render(state);this._hud();
      return {caption:this.caption,counts:this.counts,flowId:this.activeFlowId,selectedEventId:selection?.id,visibleHits:this.hits.length};
    }
    _background(){const c=this.ctx,w=this.width,h=this.height;c.fillStyle='#080f19';c.fillRect(0,0,w,h);const light=c.createRadialGradient(w*.47,h*.35,0,w*.47,h*.35,w*.72);light.addColorStop(0,'#12304738');light.addColorStop(1,'#080f1900');c.fillStyle=light;c.fillRect(0,0,w,h);c.strokeStyle='#749ab309';c.lineWidth=1;for(let x=22;x<w;x+=32){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=22;y<h;y+=32){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}}
    _text(text,x,y,{size=13,color=TEXT,font=SANS,weight=400,maxWidth,align='left'}={}){const c=this.ctx;c.fillStyle=color;c.font=`${weight} ${size}px ${font}`;c.textAlign=align;c.textBaseline='alphabetic';let s=label(text);if(maxWidth){while(s.length>1&&c.measureText(s).width>maxWidth)s=s.slice(0,-2)+'…';}c.fillText(s,x,y);c.textAlign='left';}
    _wrapped(text,x,y,width,maxLines=2,size=14,color=TEXT){const c=this.ctx;c.font=`500 ${size}px ${SANS}`;const words=label(text).split(' '),lines=[];let line='';for(const word of words){if(c.measureText(line+' '+word).width>width&&line){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);for(let i=0;i<Math.min(lines.length,maxLines);i++)this._text(lines[i]+(i===maxLines-1&&lines.length>maxLines?'…':''),x,y+i*(size+5),{size,maxWidth:width,color,weight:500});return Math.min(lines.length,maxLines);}
    _pill(text,x,y,color=MUTED){const c=this.ctx;c.font=`10px ${MONO}`;const w=c.measureText(text).width+16;rr(c,x,y,w,21,5);c.fillStyle=color+'14';c.fill();c.strokeStyle=color+'35';c.stroke();this._text(text,x+8,y+14,{size:10,color,font:MONO});return w;}
    _panel(x,y,w,h,title,subtitle,color){const c=this.ctx;rr(c,x,y,w,h,15);c.fillStyle='#0d18239a';c.fill();c.strokeStyle='#7894b321';c.lineWidth=1;c.stroke();this._text(title,x+18,y+25,{size:11,color,font:MONO,weight:500});if(subtitle)this._text(subtitle,x+18,y+46,{size:11,color:MUTED,maxWidth:w-36});}
    _card(node,{type='session',item=node,active=true,selected=false,subtitle='',detail='',color=COLORS[source(item)]||COLORS.codex,tag='',state='',compact=false}={}){
      const c=this.ctx,{x,y,w,h}=node;c.save();c.globalAlpha=active?1:.38;
      if(selected){c.shadowBlur=26;c.shadowColor=color+'45';}rr(c,x,y,w,h,11);const g=c.createLinearGradient(x,y,x,y+h);g.addColorStop(0,selected?'#21384b':'#132130');g.addColorStop(1,INK);c.fillStyle=g;c.fill();c.shadowBlur=0;c.strokeStyle=selected?color:color+'3e';c.lineWidth=selected?1.5:1;c.stroke();
      c.fillStyle=color;rr(c,x+1,y+12,3,h-24,2);c.fill();
      if(tag)this._text(tag,x+14,y+19,{size:9,color,font:MONO,maxWidth:w-35});
      const ty=y+(tag?39:25);this._wrapped(item.label||item.title||item.id,x+14,ty,w-30,compact?1:2,compact?13:14,active?TEXT:MUTED);
      if(subtitle)this._text(subtitle,x+14,y+h-(detail?27:13),{size:11,color:MUTED,maxWidth:w-30});
      if(detail)this._text(detail,x+14,y+h-12,{size:10,color:color+'bb',font:MONO,maxWidth:w-30});
      if(state){c.fillStyle=state==='active'?color:'#70839a';c.beginPath();c.arc(x+w-14,y+16,3,0,Math.PI*2);c.fill();}
      if(selected&&this.selection){const p=this.lastState.playing&&!this.lastState.reducedMotion?clamp(num(this.lastState.progress),0,1):.35;rr(c,x-4-p*3,y-4-p*3,w+8+p*6,h+8+p*6,15);c.strokeStyle=color+(this.lastState.playing?'40':'28');c.lineWidth=1;c.stroke();}
      c.restore();this.hits.push({type,id:item.id,item,rect:{x,y,w,h}});
    }
    _path(from,to,{vertical=false,offset=0}={}){let x1,y1,x2,y2,c1x,c1y,c2x,c2y;
      if(vertical){x1=from.x+from.w/2;y1=from.y+from.h;x2=to.x+to.w/2;y2=to.y;const distance=Math.max(30,(y2-y1)*.5);c1x=x1+offset;c1y=y1+distance;c2x=x2+offset;c2y=y2-distance;}
      else {const right=to.x>=from.x;x1=from.x+(right?from.w:0);y1=from.y+from.h/2;x2=to.x+(right?0:to.w);y2=to.y+to.h/2;const distance=Math.max(36,Math.abs(x2-x1)*.48);c1x=x1+(right?distance:-distance);c1y=y1+offset;c2x=x2-(right?distance:-distance);c2y=y2+offset;}
      return{x1,y1,x2,y2,c1x,c1y,c2x,c2y};
    }
    _edge(edge,from,to,{color='#7392ac',highlight=false,active=true,inferred=false,reference=false,vertical=false,offset=0,labelText='',pulse=false,hit=true}={}){
      const c=this.ctx,path=this._path(from,to,{vertical,offset});c.save();c.globalAlpha=active?1:.15;c.strokeStyle=highlight?color:color+'57';c.lineWidth=highlight?2:1.15;c.setLineDash(inferred?[3,6]:reference?[7,5]:[]);c.beginPath();c.moveTo(path.x1,path.y1);c.bezierCurveTo(path.c1x,path.c1y,path.c2x,path.c2y,path.x2,path.y2);c.stroke();c.setLineDash([]);
      if(!inferred&&!reference){const tangent=curveAt(path,.96),angle=Math.atan2(path.y2-tangent.y,path.x2-tangent.x);c.fillStyle=highlight?color:color+'88';c.beginPath();c.moveTo(path.x2,path.y2);c.lineTo(path.x2-6*Math.cos(angle-.5),path.y2-6*Math.sin(angle-.5));c.lineTo(path.x2-6*Math.cos(angle+.5),path.y2-6*Math.sin(angle+.5));c.fill();}
      if(highlight&&pulse&&this.lastState.playing&&!this.lastState.reducedMotion){const progress=clamp(num(this.lastState.progress),0,1),point=curveAt(path,progress);c.shadowColor=color;c.shadowBlur=12;c.fillStyle=color;c.beginPath();c.arc(point.x,point.y,3.5,0,Math.PI*2);c.fill();c.shadowBlur=0;}
      if(labelText){const point=curveAt(path,.5);c.font=`9px ${MONO}`;const text=label(labelText),w=Math.min(160,c.measureText(text).width+16);rr(c,point.x-w/2,point.y-10,w,20,5);c.fillStyle='#0c1825ed';c.fill();this._text(text,point.x,point.y+3,{size:9,color:highlight?color:MUTED,font:MONO,align:'center',maxWidth:w-12});}
      c.restore();if(hit)this.hits.push({type:'edge',id:edge.id,item:edge,path});return path;
    }
    _eventMatches(item){return Boolean(this.selection&&evidence(item).includes(this.selection.id));}
    _sessionMatches(session){const e=this.selection;if(!e)return false;return this._eventMatches(session)||e.metadata?.sessionId===session.id||e.metadata?.executingSessionId===session.id||(e.threadId&&String(session.threadId||session.conversationId)===String(e.threadId)&&source(session)===e.source);}
    _allowed(item){const filter=this.lastState.sourceFilter;if(!filter)return true;const identifiers=source(item)==='ci'?['ci','infrastructure','codex']:[source(item)];if(filter instanceof Set)return identifiers.some(id=>filter.has(id));if(Array.isArray(filter))return identifiers.some(id=>filter.includes(id));return identifiers.includes(filter);}
    _empty(title,copy){this._text(title,this.width/2,Math.min(this.height*.4,230),{size:20,weight:500,align:'center',maxWidth:this.width-44});this._wrapped(copy,30,Math.min(this.height*.4,230)+34,this.width-60,4,13,MUTED);this.caption=copy;this.counts={};}
    _landscape(){
      const nodes=arr(this.data.landscape?.nodes);if(!nodes.length)return this._empty('The landscape needs recorded evidence','Rebuild the archive to collect timestamped systems and their connections.');
      const mobile=this.width<600,compact=!mobile&&this.height<=500,columns=nodes.length>9?4:3,margin=mobile?18:28,columnGap=this.width<750?12:20,w=mobile?Math.min(230,this.width-110):columns===4?Math.min(230,(this.width-margin*2-columnGap*3)/4):clamp((this.width-140)/3,162,230),h=compact?78:92;let placements=[];
      const order={slack:[0,0],docs:[0,1],codex:[1,0],flujo:[1,1],'codex-team':[0,2],'flujo-team':[1,2],github:[2,0],'local-ci':[2,1],'modal-ci':[2,2]};
      if(mobile){const preferred=['slack','codex','flujo','github','infrastructure','docs','codex-team','flujo-team','local-ci','modal-ci'],byId=new Map(nodes.map(item=>[item.id,item])),ordered=[...preferred.filter(id=>byId.has(id)).map(id=>byId.get(id)),...nodes.filter(item=>!preferred.includes(item.id))];placements=ordered.map((item,i)=>({...item,x:margin+(i%2?Math.min(68,this.width-w-36):0),y:72+i*128,w,h}));}
      else {const available=this.width-margin*2-w,step=available/(columns-1),occupied=new Set(nodes.filter(item=>order[item.id]).map(item=>order[item.id].join(':'))),extraSlots=[];
        // Reserve every known component before allocating extra captured sources.
        for(let row=0;row<Math.max(3,Math.ceil(nodes.length/columns));row++)for(const col of columns===4?[3,0,1,2]:[0,1,2])if(!occupied.has(`${col}:${row}`))extraSlots.push([col,row]);
        placements=nodes.map(item=>{const [col,row]=order[item.id]||extraSlots.shift();return{...item,x:margin+col*step,y:(compact?44:82)+row*(compact?h+12:116),w,h};});}
      const map=new Map(placements.map(node=>[node.id,node]));
      this._text(compact?'THE DEVELOPMENT SYSTEM · EVIDENCE-DRIVEN SIGNALS':'THE DEVELOPMENT SYSTEM',margin,27,{size:11,color:MUTED,font:MONO,maxWidth:this.width-margin*2});if(!compact)this._text('Each signal belongs to an original event.',margin,48,{size:13,color:TEXT,maxWidth:this.width-50});
      if(!mobile&&!compact){['PEOPLE & CONTEXT','ORCHESTRATION','SHIPPING & VERIFICATION',...(columns===4?['EXECUTION HOSTS']:[])].forEach((s,i)=>this._text(s,margin+i*(this.width-margin*2-w)/(columns-1),69,{size:9,color:MUTED,font:MONO,maxWidth:w}));}
      const allEdges=arr(this.data.landscape?.edges),selectedRoutes=[];const e=this.selection;
      for(const edge of allEdges){const from=map.get(edge.from),to=map.get(edge.to);if(!from||!to)continue;const basis=String(edge.basis||''),inferred=/infer|editorial/i.test(basis),reference=/shared|reference/i.test(basis);const exact=this._eventMatches(edge),active=stamp(edge.firstTimestamp)<=this.now;
        if(reference&&!exact&&!this.lastState.allLinks||mobile&&!exact&&!this.lastState.allLinks)continue;this._edge(edge,from,to,{active,inferred,reference,vertical:mobile,color:COLORS[source(from)]||MUTED,highlight:exact&&!inferred,labelText:exact?(inferred?'Inferred relationship':reference?'Shared reference':edge.label):'',pulse:exact&&!inferred,offset:(allEdges.indexOf(edge)%3-1)*20});if(exact&&!inferred)selectedRoutes.push(edge);
      }
      // Route every explicit reference, including events beyond aggregate edge evidence samples.
      if(e){const from=map.get(e.source),targets=new Set();for(const ref of arr(e.references)){for(const [s,time] of this.referenceSources.get(normalizeRef(ref))||[])if(s!==e.source&&time<=this.now)targets.add(s);if(/github\.com\//i.test(ref)&&e.source!=='github')targets.add('github');if(/slack\.com\/archives\//i.test(ref)&&e.source!=='slack')targets.add('slack');}
        for(const target of targets){const to=map.get(target);if(!from||!to||selectedRoutes.some(edge=>edge.from===from.id&&edge.to===to.id))continue;const edge={id:`reference:${e.id}:${target}`,from:from.id,to:to.id,label:'Explicit shared reference',basis:'Shared URL reference; does not establish causation',eventIds:[e.id],references:e.references};this._edge(edge,from,to,{reference:true,vertical:mobile,color:COLORS[e.source]||MUTED,highlight:true,labelText:'Explicit reference',pulse:true});selectedRoutes.push(edge);}
      }
      for(const node of placements){const selected=source(node)===e?.source&&node.id===e?.source||this._eventMatches(node);const count=upperBound(this.sourceTimes.get(node.source)||[],this.now),sessions=upperBound(this.sessionTimes.get(node.source)||[],this.now);let detail=node.id.includes('team')?`${sessions} captured sessions`:count?`${count.toLocaleString()} recorded events`:'First evidence appears later';this._card(node,{type:'system',item:node,compact,active:stamp(node.firstTimestamp)<=this.now&&this._allowed(node),selected,tag:node.id.includes('ci')?'VERIFICATION':source(node).toUpperCase(),subtitle:node.id.includes('team')?'Inspect parallel agent sessions':node.id==='github'?'Commits · pull requests · reviews':node.id==='slack'?'Messages · threads · decisions':node.id==='flujo'?'Conversations · saved flow graphs':node.id==='codex'?'Chats · subagents · tool execution':node.id==='docs'?'Rules · contracts · plans':node.id==='infrastructure'?'Containers · machines · build logs':'Captured automation evidence',detail,color:COLORS[source(node)]||COLORS.ci});}
      this.caption=e?`${selectedRoutes.length} evidence link${selectedRoutes.length===1?'':'s'} for this event. Dashed references establish a shared artifact; dotted links are inferred.`:'Select an event to trace its recorded references. Connections stay still while paused.';this.counts={nodes:nodes.length,routes:selectedRoutes.length};
    }
    _agents(){
      const all=arr(this.data.topology?.sessions).filter(session=>this._allowed(session));if(!all.length)return this._empty('No agent sessions captured','The rebuild needs Codex session lineage or persisted FLUJO conversation records.');
      const selected=all.find(session=>session.id===this.selection?.metadata?.executingSessionId)||all.find(session=>this._sessionMatches(session)),filter=this.lastState.sessionFilter;let pool=all,focus=filter?this.sessionById.get(filter):null;
      if(focus){const family=new Set([focus.id]);let changed=true;while(changed){changed=false;for(const session of all)if(session.parentId&&family.has(session.parentId)&&!family.has(session.id)){family.add(session.id);changed=true;}}let ancestor=focus;for(let i=0;i<30&&ancestor?.parentId;i++){family.add(ancestor.parentId);ancestor=this.sessionById.get(ancestor.parentId);}const contacts=new Set();for(const edge of arr(this.data.topology?.agentEdges))if(edge.kind!=='node_transition'){if(family.has(edge.from))contacts.add(edge.to);if(family.has(edge.to))contacts.add(edge.from);}for(const id of contacts)family.add(id);pool=all.filter(s=>family.has(s.id));}
      const mobile=this.width<600,margin=mobile?18:26,cardW=mobile?Math.min(250,this.width-65):clamp((this.width-95)/3,170,230),cardH=107,colGap=30;
      const stable=this._agentLayout(pool,focus,cardW,cardH,margin,mobile),{byId,children,flujoStart}=stable,active=s=>stamp(s.startedAt)<=this.now&&(!stamp(s.endedAt)||stamp(s.endedAt)>=this.now),chosenIds=new Set(stable.base);
      // Selection adds evidence context without moving the fixed, chronological family slots.
      if(selected){let current=selected;for(let i=0;i<20&&current;i++){chosenIds.add(current.id);current=byId.get(current.parentId);}for(const child of(children.get(selected.id)||[]).slice(0,focus?14:3))chosenIds.add(child.id);}
      const observed=byId.get(this.selection?.metadata?.observedInSessionId||this.selection?.metadata?.sessionId)||selected;
      if(observed){chosenIds.add(observed.id);for(const child of(children.get(observed.id)||[]).slice(0,32))chosenIds.add(child.id);if(stable.map.has(observed.id))this.flowFollow={key:`agents:${stable.key}:${observed.id}`,rect:stable.map.get(observed.id)};}
      const map=new Map([...stable.map].filter(([id])=>chosenIds.has(id))),placements=[...map.values()].map(item=>({item}));
      const codexCount=all.filter(s=>source(s)==='codex').length,flujoCount=all.filter(s=>source(s)==='flujo').length;
      this._text(focus?'AGENT FAMILY · RECORDED LINEAGE':'PARALLEL CHATS & SUBAGENTS',margin,28,{size:11,color:MUTED,font:MONO});this._text(focus?focus.label:`${codexCount} Codex sessions · ${flujoCount} FLUJO conversations`,margin,49,{size:13,maxWidth:this.width-margin*2});
      if(placements.some(p=>source(p.item)==='codex'))this._text('CODEX',margin,66,{size:10,color:COLORS.codex,font:MONO});if(placements.some(p=>source(p.item)==='flujo'))this._text('FLUJO',margin,flujoStart-18,{size:10,color:COLORS.flujo,font:MONO});
      const recorded=this.aggregatedEdges||[],parentEdges=[];for(const node of map.values())if(map.has(node.parentId)&&!recorded.some(edge=>edge.from===node.parentId&&edge.to===node.id&&/spawn|fork|parent/.test(edge.kind))){parentEdges.push({id:`parent:${node.id}`,from:node.parentId,to:node.id,kind:'parent',timestamp:node.startedAt,basis:node.parentBasis||'Persisted parent session ID',eventIds:[]});}
      for(const edge of [...parentEdges,...recorded]){const from=map.get(edge.from),to=map.get(edge.to);if(!from||!to||edge.kind==='node_transition')continue;const exact=this._eventMatches(edge);this._edge(edge,from,to,{color:COLORS[source(to)]||COLORS.codex,highlight:exact,active:stamp(edge.timestamp||to.startedAt)<=this.now,inferred:!causal(edge),vertical:mobile&&Math.abs(from.x-to.x)<60,offset:edge.kind==='steer'?24:0,labelText:exact?`${edge.kind}${edge.instances>1?` · ${edge.instances} records`:''}`:edge.kind==='runtime_binding'?'Current runtime binding':'',pulse:exact&&causal(edge)});}
      for(const node of map.values()){const s=byId.get(node.id),count=evidence(s).length,start=stamp(s.startedAt),end=stamp(s.endedAt),available=start<=this.now,isActive=active(s),selectedHere=this._sessionMatches(s);const childCount=(children.get(s.id)||[]).length;this._card(node,{type:'session',item:s,active:available,selected:selectedHere,tag:`${source(s).toUpperCase()} · ${label(s.role||s.agentRole|| (s.parentId?'SUBAGENT':'CHAT')).toUpperCase()}`,subtitle:`${count.toLocaleString()} events${childCount?` · ${childCount} children`:''}`,detail:available?`${isActive?'OPEN SESSION':'ENDED'} · ${compactDate(s.startedAt)}`:`STARTS ${compactDate(s.startedAt)}`,state:isActive?'active':'ended'});
        // A lifespan bar uses real timestamps and never implies unrecorded execution.
        const min=stamp(this.data.range?.start||this.events[0]?.timestamp)||start,max=stamp(this.data.range?.end||this.events[this.events.length-1]?.timestamp)||this.now,span=Math.max(1,max-min),barX=node.x+14,barY=node.y+node.h-5,barW=node.w-28;this.ctx.fillStyle='#62798d25';this.ctx.fillRect(barX,barY,barW,2);this.ctx.fillStyle=COLORS[source(s)]||MUTED;this.ctx.fillRect(barX+clamp((start-min)/span,0,1)*barW,barY,Math.max(2,(clamp(((end||stamp(s.lastActivityAt)||start)-min)/span,0,1)-clamp((start-min)/span,0,1))*barW),2);
      }
      const rootVisible=new Set([...map.values()].map(n=>n.id));this.caption=`${rootVisible.size} / ${pool.length} sessions in this focus. Positions stay fixed through message replay. Solid arrows use captured parent or dispatch evidence; dotted links are inferred.`;this.counts={sessions:all.length,visible:rootVisible.size,active:all.filter(active).length};
    }
    _flows(){
      const flows=arr(this.data.topology?.flows);if(!flows.length)return this._empty('No saved FLUJO graphs captured','Persisted flow definitions are required to show actual agent nodes and execution paths.');
      const e=this.selection,m=e?.metadata||{},flow=this._resolveFlow();if(!flow)return this._empty('No saved graph attribution','This event has no recorded flow definition.');this.activeFlowId=flow.id;const availableNow=!flowStamp(flow)||flowStamp(flow)<=this.now;
      const nodes=arr(flow.nodes);if(!nodes.length)return this._empty('Saved graph has no nodes',flow.label||flow.id);const mobile=this.width<600,margin=mobile?18:28,cardW=mobile?Math.min(240,this.width-70):184,cardH=91;
      const {map,positioned}=this._flowLayout(flow,cardW,cardH,margin);
      this._text(availableNow?'FLUJO · THE ACTUAL SAVED GRAPH':'FLUJO · GRAPH CAPTURED LATER',margin,27,{size:11,color:availableNow?COLORS.flujo:MUTED,font:MONO});this._text(flow.label||flow.name||flow.id,margin,53,{size:18,weight:500,color:availableNow?TEXT:MUTED,maxWidth:this.width-margin*2});this._pill(availableNow?'DECLARED GRAPH SNAPSHOT':'DECLARED SNAPSHOT · AFTER PLAYHEAD',margin,69,availableNow?COLORS.flujo:MUTED);this._text(availableNow?`${nodes.length} nodes · ${arr(flow.edges).length} edges${positioned?' · saved order, readable spacing':' · graph layout'}`:`First captured ${compactDate(flow.availableFrom)} · execution is not implied`,margin,103,{size:10,color:MUTED,font:MONO,maxWidth:this.width-margin*2});
      const nodeId=m.nodeId||m.currentNodeId||m.flowNodeId||m.executionNodeId||m.node_id||m.executionTracker?.nodeId||m.tracker?.nodeId;
      const belongs=availableNow&&e?.source==='flujo'&&(m.flowId?m.flowId===flow.id:m.flowDefinitionId?m.flowDefinitionId===flow.flowDefinitionId:true);
      const execution=belongs&&(/tracker|node|execute|transition/i.test(e?.kind||'')||/node:|handoff|model:dispatch|tool:|subflow:/i.test(m.eventType||'')||Boolean(m.executionTracker||m.executedNodeId||m.nodeEvent||m.executionBasis||m.nodeTracker));
      const contextOnly=belongs&&!execution&&Boolean(nodeId&&m.nodeAttributionBasis),activeId=execution?(m.eventType==='handoff'?m.toNodeId:m.executedNodeId||nodeId):contextOnly?nodeId:null;
      if(activeId&&map.has(activeId))this.flowFollow={key:[flow.id,m.executingSessionId||m.sessionId||e.threadId||'',activeId].join('|'),rect:map.get(activeId)};
      let transitions=arr(this.edgeEvents.get(e?.id)).filter(edge=>edge.kind==='node_transition'&&(!edge.flowId||edge.flowId===flow.id));const fromId=m.fromNodeId||m.previousNodeId,toId=m.toNodeId||activeId;
      for(const edge of arr(flow.edges)){const from=map.get(edge.from||edge.source),to=map.get(edge.to||edge.target);if(!from||!to)continue;const exact=availableNow&&(this._eventMatches(edge)||Boolean(execution&&fromId===from.id&&toId===to.id)||transitions.some(t=>(t.from===from.id||t.fromNodeId===from.id)&&(t.to===to.id||t.toNodeId===to.id)));const item={...edge,basis:exact?'Recorded node execution transition':'Declared flow definition; not execution',eventIds:exact?[e.id]:evidence(edge)};this._edge(item,from,to,{color:COLORS.flujo,active:availableNow,highlight:exact,reference:!exact,vertical:Math.abs(from.x-to.x)<cardW*.6,labelText:exact?'Recorded transition':edge.label||'',pulse:exact});}
      for(const node of map.values()){const selected=node.id===activeId,original=nodes.find(n=>n.id===node.id),item={...original,id:node.id,flowId:flow.id,eventIds:selected?[e.id]:evidence(original),attributionBasis:selected?m.nodeAttributionBasis||m.basis:undefined};this._card(node,{type:'flowNode',item,active:availableNow,selected,compact:true,tag:label(node.type||node.kind||'AGENT NODE').toUpperCase(),subtitle:node.role||node.model||node.agent||'Saved graph definition',detail:!availableNow?'DECLARED SNAPSHOT · RECORDED LATER':selected?(contextOnly?'LAST RECORDED NODE CONTEXT':'RECORDED NODE EVENT'):'DECLARED NODE · INSPECT CONFIG',color:COLORS.flujo});}
      this.caption=!availableNow?`This declared graph was first captured ${compactDate(flow.availableFrom)}, after the current playhead. It is dimmed; no historical execution is implied.`:contextOnly?`Message attributed to the last recorded node ${activeId}; no execution transition is invented.`:activeId?`Recorded node event at ${activeId}. Motion follows captured transitions only.`:`Showing persisted flow layout. This event has no recorded node execution marker.`;this.counts={nodes:nodes.length,edges:arr(flow.edges).length,snapshots:flows.length};
    }
    _infrastructure(){
      const infra=this.data.infrastructure||{},machines=arr(infra.machines);if(!machines.length&&!arr(infra.builds).length&&!arr(infra.deployments).length)return this._empty('No observed machine records','The rebuild requires Docker inspect output, authenticated Fly machine records, or recorded CI executions.');
      const mobile=this.width<600,margin=mobile?18:24,gap=18,colW=mobile?this.width-margin*2:(this.width-margin*2-gap*2)/3,providerGroups=[{id:'local',label:'LOCAL WORKSTATION',subtitle:'Windows · Docker Desktop',color:COLORS.docker,providers:['docker','local']},{id:'fly',label:'FLY.IO',subtitle:'Recorded regions & machine lifecycles',color:COLORS.fly,providers:['fly']},{id:'modal',label:'MODAL',subtitle:'Recorded cloud CI executions',color:COLORS.modal,providers:['modal']}];
      this._text('WHERE THE BUILD ACTUALLY RAN',margin,27,{size:11,color:MUTED,font:MONO});this._text('Machines, builds, and deployments with original evidence.',margin,49,{size:13,maxWidth:this.width-margin*2});let stackedY=73,visible=0,matched=0;
      const perPage=mobile?2:this.height>740?4:this.height>620?3:2,selectionChanged=this.infraSelection!==this.selection?.id;this.infraSelection=this.selection?.id;
      for(let i=0;i<providerGroups.length;i++){const group=providerGroups[i],allItems=machines.filter(machine=>group.providers.includes(machine.provider)),deployments=arr(infra.deployments).filter(item=>group.providers.includes(item.provider)),builds=arr(infra.builds).filter(item=>group.providers.includes(item.provider));
        const pageCount=Math.max(1,Math.ceil(allItems.length/perPage)),matchedIndex=allItems.findIndex(machine=>this._eventMatches(machine)||this.selection?.metadata?.machineId===machine.id);if(selectionChanged&&matchedIndex>=0)this.infraPages.set(group.id,Math.floor(matchedIndex/perPage));const page=clamp(this.infraPages.get(group.id)||0,0,pageCount-1),items=allItems.slice(page*perPage,(page+1)*perPage);
        const records=[...builds.map(item=>({...item,recordType:'BUILD'})),...deployments.map(item=>({...item,recordType:'DEPLOYMENT'}))].sort((a,b)=>(this._eventMatches(b)?1e15:0)+(stamp(b.timestamp||b.startedAt)<=this.now?1e14:0)+stamp(b.timestamp||b.startedAt)-(this._eventMatches(a)?1e15:0)-(stamp(a.timestamp||a.startedAt)<=this.now?1e14:0)-stamp(a.timestamp||a.startedAt)).slice(0,2);
        const x=mobile?margin:margin+i*(colW+gap),y=mobile?stackedY:73,machineHeight=items.length?items.length*126+(pageCount>1?34:0):records.length?24:128,recordsHeight=records.length?32+records.length*83:0,h=Math.max(210,82+machineHeight+recordsHeight+(builds.length||deployments.length?44:0));this._panel(x,y,colW,h,group.label,group.subtitle,group.color);
        if(!items.length&&!records.length)this._wrapped('No observed machine lifecycle in this capture.',x+18,y+97,colW-36,3,13,MUTED);
        for(let j=0;j<items.length;j++){const machine=items[j],node={x:x+12,y:y+67+j*126,w:colW-24,h:108},events=this.machineEvents.get(machine.id)||[],observed=stamp(machine.lastObservedAt),first=stamp(machine.createdAt||machine.firstTimestamp),prior=events.filter(event=>stamp(event.timestamp)<=this.now),lifecycles=prior.filter(event=>/^(create|created|start|started|stop|stopped|destroy|destroyed|delete|deleted|launch|launched|restart|restarted|exit|exited|suspend|suspended|resume|resumed)$/i.test(event.metadata?.lifecycle||'')||Boolean(event.metadata?.state&& !/^(log|snapshot)$/i.test(event.metadata?.lifecycle||''))),latest=lifecycles[lifecycles.length-1],selected=this._eventMatches(machine)||this.selection?.metadata?.machineId===machine.id,lifecycle=latest?.metadata?.lifecycle,snapshotVisible=machine.currentSnapshot&&observed&&observed<=this.now&&observed>=stamp(latest?.timestamp);let state=first>this.now?'FIRST EVIDENCE LATER':lifecycle?`RECORDED ${lifecycle.toUpperCase()}`:machine.currentSnapshot?'CURRENT SNAPSHOT ONLY':'NO HISTORICAL STATE';if(snapshotVisible)state=`OBSERVED ${label(machine.state||'machine').toUpperCase()}`;
          const logs=prior.filter(event=>event.metadata?.lifecycle==='log').length;this._card(node,{type:'machine',item:machine,active:!first||first<=this.now,selected,color:group.color,tag:`${(machine.provider||group.id).toUpperCase()} · ${machine.location||'LOCATION NOT CAPTURED'}`,subtitle:machine.image?String(machine.image).split('/').pop():machine.app||machine.service||'Observed execution target',detail:state,state:snapshotVisible?/^(running|started)$/i.test(machine.state||'')?'active':'':/^(start|create|launch|restart|resume)$/.test(lifecycle||'')?'active':''});this._text((machine.createdAt?`Created ${compactDate(machine.createdAt)}`:`Observed ${compactDate(machine.firstTimestamp||machine.lastObservedAt)}`)+(logs?` · ${logs} log lines`:''),node.x+14,node.y+node.h+16,{size:9,color:MUTED,font:MONO,maxWidth:node.w-28});visible++;if(selected)matched++;
        }
        if(pageCount>1){const pagerY=y+67+items.length*126+2;this._text(`${page*perPage+1}–${Math.min(allItems.length,(page+1)*perPage)} / ${allItems.length} machines`,x+18,pagerY+17,{size:10,color:MUTED,font:MONO,maxWidth:colW-90});for(const [direction,text,index] of [[-1,'←',0],[1,'→',1]]){const bx=x+colW-73+index*30;rr(this.ctx,bx,pagerY,26,25,5);this.ctx.fillStyle='#193047';this.ctx.fill();this.ctx.strokeStyle='#6384a547';this.ctx.stroke();this._text(text,bx+13,pagerY+17,{size:14,color:group.color,align:'center'});this.controls.push({x:bx,y:pagerY,w:26,h:25,action:()=>this.infraPages.set(group.id,(page+direction+pageCount)%pageCount)});}}
        if(records.length){const recordY=y+67+machineHeight+22;this._text('BUILD & DEPLOYMENT EVIDENCE',x+18,recordY-9,{size:9,color:group.color,font:MONO,maxWidth:colW-36});records.forEach((record,j)=>{const eventId=evidence(record).find(id=>this.eventById.has(id)),item={...record,id:eventId||record.id,label:record.app||record.service||record.label||`${record.provider} ${record.recordType.toLowerCase()}`};this._card({x:x+12,y:recordY+j*83,w:colW-24,h:74},{type:'event',item,compact:true,active:stamp(record.timestamp||record.startedAt)<=this.now,selected:this._eventMatches(record),color:group.color,tag:record.recordType,subtitle:`${record.state||'Recorded output'} · ${compactDate(record.timestamp||record.startedAt)}`,detail:''});});}
        if(deployments.length||builds.length){this._text(`${builds.length} builds · ${deployments.length} deployments`,x+18,y+h-16,{size:10,color:MUTED,font:MONO,maxWidth:colW-36});}
        if(mobile)stackedY+=h+gap;
      }
      this.caption=`${machines.length} observed machines · ${arr(infra.builds).length} builds · ${arr(infra.deployments).length} deployment records. Use provider arrows to inspect every machine; current snapshots are separate from timestamped lifecycle records.`;this.counts={machines:machines.length,visibleMachines:visible,selected:matched,builds:arr(infra.builds).length,deployments:arr(infra.deployments).length};
    }
    _hud(){const c=this.ctx,w=this.width,h=this.height;c.save();c.setTransform(this.dpr,0,0,this.dpr,0,0);const fade=c.createLinearGradient(0,h-82,0,h);fade.addColorStop(0,'#080f1900');fade.addColorStop(.4,'#080f19ed');fade.addColorStop(1,'#080f19');c.fillStyle=fade;c.fillRect(0,h-82,w,82);this._text(this.lastState.playing?'● LIVE EVENT REPLAY':'Ⅱ FRAME PAUSED',18,h-40,{size:9,color:this.lastState.playing?COLORS.github:MUTED,font:MONO});this._text(this.lastState.view==='landscape'?'Only evidence creates a signal':'Drag to pan · Ctrl + scroll to zoom · Double-click to reset',18,h-21,{size:10,color:MUTED,maxWidth:w-36});if(this.hover){const text=label(this.hover.label||this.hover.id),tooltipW=Math.min(w-30,Math.max(130,text.length*6.4+24));rr(c,15,h-111,tooltipW,29,7);c.fillStyle='#182b3bef';c.fill();c.strokeStyle='#8eb2ce55';c.stroke();this._text(text,27,h-92,{size:11,maxWidth:tooltipW-20});}
      this.minimap=null;const bounds=this._bounds();if(bounds&&(bounds.h*this.camera.scale>h+100||bounds.w*this.camera.scale>w+100)){const boxW=w<600?65:95,boxH=65,scale=Math.min(boxW/bounds.w,boxH/bounds.h),mapW=Math.max(24,bounds.w*scale),mapH=Math.max(24,bounds.h*scale),x=w-mapW-18,y=h-mapH-94;rr(c,x-6,y-6,mapW+12,mapH+12,7);c.fillStyle='#101d2cec';c.fill();c.strokeStyle='#7c9ab33b';c.stroke();c.save();c.beginPath();c.rect(x,y,mapW,mapH);c.clip();for(const hit of this.hits){if(!hit.rect)continue;const r=hit.rect;c.fillStyle=COLORS[source(hit.item)]||COLORS[hit.item.provider]||MUTED;c.globalAlpha=.6;c.fillRect(x+(r.x-bounds.x)*scale,y+(r.y-bounds.y)*scale,Math.max(2,r.w*scale),Math.max(2,r.h*scale));}c.globalAlpha=1;c.strokeStyle='#e5f0fb99';c.lineWidth=1;c.strokeRect(x+(-this.camera.x/this.camera.scale-bounds.x)*scale,y+(-this.camera.y/this.camera.scale-bounds.y)*scale,w/this.camera.scale*scale,h/this.camera.scale*scale);c.restore();this.minimap={x,y,w:mapW,h:mapH,scale,bounds};this._text('MAP',x,y-12,{size:8,color:MUTED,font:MONO});}c.restore();}
  }
  window.HistoryGraphScene=HistoryGraphScene;
})();
